### ISSUE TITLE
Mapa y Contacto

### ISSUE THREAD

**Issue by juanbono** [fedesanches/WorkshopWeb#4]
Modificar la parte del mapa, para que muestre Campana y el Contacto. Poner ambos en un formulario, donde permita escribir un mail que sera enviado a la casilla del workshop. Poner una imagen de la facultad de fondo.

**Comment by juanbono** [comment]
@fedesanches de aca solo faltaria el mail?

**Comment by fedesanches** [comment]
si

2017-09-14 12:41 GMT-03:00 Juan Bono <notifications@github.com>:

**Comment by juanbono** [comment]
Aca faltaria la informacion de contacto que esta en el google site:
```
Universidad Tecnológica Nacional - Facultad Regional Delta. 
San Martín 1171, Campana, Bs. As., Argentina 03489 - 420400 www.frd.utn.edu.ar @utndelta
```
